import 'dotenv/config';
import { readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import db, { saveFact, factsAbout, upsertPerson } from '../src/db.js';
import { getProfileConfig } from '../src/config.js';

/**
 * Seed the assistant's baseline knowledge about the owner into the `facts` table.
 *
 * Source of truth:
 *   - People come from config/profile.json (the `people` array), written by the
 *     onboarding "Mirror" conversation (npm run onboard).
 *   - Atomic facts come from context/seeds/facts.json (also generated by onboarding;
 *     the repo ships a neutral sample at context/_examples/facts.json).
 *
 * This is the generic successor to the old hardcoded seed. It seeds nothing about
 * any specific person — everything is read from the operator's own profile/facts.
 *
 * Idempotent:
 *   - Inner-circle people upsert by exact (case-insensitive) name; re-running skips
 *     anyone already present (from a prior seed or Apple Contacts sync). Name-subject
 *     facts then auto-bind to that person row by person_id.
 *   - Every JSON fact inserts with mode:'append', skipping any (subject, predicate,
 *     object) already active. Re-running merges rather than duplicating.
 *   - Always writes one marker fact (__seed__ / ran) so `npm run doctor` can tell the
 *     seed ran even when no facts were configured.
 *
 * Usage: tsx scripts/seed-facts.ts          (or: npm run seed:facts)
 *        tsx scripts/seed-facts.ts --dry     (preview, no writes)
 */

const __dirname = dirname(fileURLToPath(import.meta.url));
const FACTS_PATH = join(__dirname, '..', 'context', 'seeds', 'facts.json');

const DRY = process.argv.includes('--dry');

interface SeedFact {
  subject: string;
  predicate: string;
  object: string;
  fact_type?: string;
  confidence?: number;
  valid_until?: string;
}

function alreadyExists(subject: string, predicate: string, object: string): boolean {
  const existing = factsAbout(subject, 200);
  const pNorm = predicate.toLowerCase();
  return existing.some((f) => f.predicate === pNorm && f.object === object);
}

// upsertPerson dedups on email/phone/linkedin, NOT name — so seeding handle-less
// rows blindly would create a duplicate person on every run. Guard on an exact
// case-insensitive name match: if the person already exists, skip — facts still
// auto-bind to that row by name.
function personExistsByName(name: string): boolean {
  const hit = db
    .prepare('SELECT id FROM people WHERE name = ? COLLATE NOCASE LIMIT 1')
    .get(name) as { id: number } | undefined;
  return !!hit;
}

function loadFacts(): SeedFact[] {
  if (!existsSync(FACTS_PATH)) {
    console.log(`[seed] no ${FACTS_PATH} — run npm run onboard, or copy context/_examples/facts.json. Seeding people + marker only.`);
    return [];
  }
  try {
    return JSON.parse(readFileSync(FACTS_PATH, 'utf-8')) as SeedFact[];
  } catch (err) {
    console.warn(`[seed] failed to parse ${FACTS_PATH}: ${(err as Error).message}. Seeding people + marker only.`);
    return [];
  }
}

function main() {
  const profile = getProfileConfig();
  const people = profile.people || [];
  const facts = loadFacts();
  console.log(`[seed] ${people.length} people from profile, ${facts.length} facts from disk${DRY ? ' (dry run)' : ''}`);

  // People first so name-subject facts auto-bind.
  let peopleWrote = 0;
  let peopleSkipped = 0;
  for (const p of people) {
    if (!p.name) continue;
    if (personExistsByName(p.name)) { peopleSkipped += 1; continue; }
    if (DRY) { console.log(`  · would create person: ${p.name}`); peopleWrote += 1; continue; }
    upsertPerson({ name: p.name, relationship: p.relationship, role: p.role, notes: p.notes });
    peopleWrote += 1;
  }
  console.log(`[seed] inner-circle people: ${peopleWrote} ${DRY ? 'would be ' : ''}created, ${peopleSkipped} already present`);

  let wrote = 0;
  let skipped = 0;
  for (const f of facts) {
    if (!f.subject || !f.predicate || !f.object) {
      console.warn(`  ! skipping malformed fact: ${JSON.stringify(f)}`);
      continue;
    }
    if (alreadyExists(f.subject, f.predicate, f.object)) { skipped += 1; continue; }
    if (DRY) {
      console.log(`  · would save: ${f.subject} / ${f.predicate} / ${f.object.slice(0, 60)}…`);
      wrote += 1;
      continue;
    }
    saveFact({
      subject: f.subject,
      predicate: f.predicate,
      object: f.object,
      fact_type: f.fact_type || 'fact',
      confidence: f.confidence,
      valid_until: f.valid_until,
      source: 'manual',
      mode: 'append',
    });
    wrote += 1;
  }

  // Marker fact so doctor can confirm the seed ran (independent of fact count).
  if (!DRY && !alreadyExists('__seed__', 'ran', 'true')) {
    saveFact({ subject: '__seed__', predicate: 'ran', object: 'true', fact_type: 'fact', source: 'manual', mode: 'append' });
  }

  console.log(`\n[seed] done: ${wrote} ${DRY ? 'would be ' : ''}written, ${skipped} skipped (already active)`);
}

main();
