import { readFileSync, existsSync } from 'fs';
import { profilePath } from './paths.js';

// ─────────────────────────────────────────────────────────────────────────────
// Profile config — the single source of truth for who this assistant is and who
// it serves. Generated by `npm run onboard` (the Mirror conversation) into
// config/profile.json (gitignored). The repo ships config/profile.example.json.
//
// Everything that used to be hardcoded to one person (bot name, owner name,
// family name, inner circle, which groups exist) reads from here. When no
// profile.json is present the loader returns safe, generic defaults so the repo
// still typechecks and boots — `initUsers()` won't throw on a fresh clone.
// ─────────────────────────────────────────────────────────────────────────────

const PROFILE_PATH = profilePath;

export type Tone = 'direct' | 'warm' | 'playful';
export type Role = 'admin' | 'member' | 'child';

/** A person who can message the assistant (resolves from a phone/email handle). */
export interface ProfileUser {
  id: string;
  name: string;
  tone: Tone;
  role: Role;
  /** Registry keys of the groups this user may use. */
  allowedGroups: string[];
  /** Env var holding this user's phone (default `USER_<ID uppercased>`). */
  phoneEnv?: string;
  /** Env var holding this user's email (default `USER_<ID uppercased>_EMAIL`). */
  emailEnv?: string;
}

/** A person in the CRM seed (inner circle). Not necessarily a messaging user. */
export interface ProfilePerson {
  name: string;
  relationship?: string;
  role?: string;
  notes?: string;
}

export interface ProfileConfig {
  /** What the assistant is called (e.g. "Milo"). */
  botName: string;
  /** The @-trigger required in group chats (e.g. "@milo"). */
  triggerWord: string;
  /** A collective noun for the household/team, used in the soul line. */
  householdName: string;
  /** The admin user — all system-initiated work runs as this user. */
  owner: ProfileUser;
  /** Additional messaging users (e.g. a partner). */
  members: ProfileUser[];
  /** CRM seed people written by the seed script. */
  people: ProfilePerson[];
  /** Group registry keys this deployment turns on. */
  groupsEnabled: string[];
}

// Generic, person-free defaults. A fresh clone with no profile.json still boots.
const DEFAULTS: ProfileConfig = {
  botName: 'Assistant',
  triggerWord: process.env.TRIGGER_WORD || '@assistant',
  householdName: 'household',
  owner: {
    id: 'owner',
    name: 'Owner',
    tone: 'direct',
    role: 'admin',
    allowedGroups: ['admin', 'home', 'work', 'finance', 'health', 'reflection', 'brain-pulse', 'content'],
    phoneEnv: 'USER_OWNER',
    emailEnv: 'USER_OWNER_EMAIL',
  },
  members: [],
  people: [],
  groupsEnabled: ['admin'],
};

let cached: ProfileConfig | null = null;

function normalizeUser(raw: any, fallbackId: string): ProfileUser {
  const id = String(raw?.id || fallbackId);
  return {
    id,
    name: String(raw?.name || id),
    tone: (raw?.tone as Tone) || 'direct',
    role: (raw?.role as Role) || (fallbackId === 'owner' ? 'admin' : 'member'),
    allowedGroups: Array.isArray(raw?.allowedGroups) ? raw.allowedGroups.map(String) : [],
    phoneEnv: raw?.phoneEnv || `USER_${id.toUpperCase()}`,
    emailEnv: raw?.emailEnv || `USER_${id.toUpperCase()}_EMAIL`,
  };
}

/** Load (and cache) the profile config, falling back to generic defaults. */
export function getProfileConfig(): ProfileConfig {
  if (cached) return cached;

  if (!existsSync(PROFILE_PATH)) {
    cached = DEFAULTS;
    return cached;
  }

  try {
    const raw = JSON.parse(readFileSync(PROFILE_PATH, 'utf-8'));
    cached = {
      botName: String(raw.botName || DEFAULTS.botName),
      triggerWord: String(raw.triggerWord || process.env.TRIGGER_WORD || DEFAULTS.triggerWord),
      householdName: String(raw.householdName || DEFAULTS.householdName),
      owner: normalizeUser(raw.owner, 'owner'),
      members: Array.isArray(raw.members)
        ? raw.members.map((m: any, i: number) => normalizeUser(m, m?.id || `member${i + 1}`))
        : [],
      people: Array.isArray(raw.people) ? raw.people : [],
      groupsEnabled: Array.isArray(raw.groupsEnabled) ? raw.groupsEnabled.map(String) : DEFAULTS.groupsEnabled,
    };
    return cached;
  } catch (err) {
    console.warn(`[config] failed to parse ${PROFILE_PATH}, using defaults:`, (err as Error).message);
    cached = DEFAULTS;
    return cached;
  }
}

/** Reset the in-memory cache (used by onboarding after it writes a new profile). */
export function resetProfileCache(): void {
  cached = null;
}

export function getBotName(): string {
  return getProfileConfig().botName;
}

export function getOwner(): ProfileUser {
  return getProfileConfig().owner;
}
