import { readFileSync, existsSync, readdirSync } from 'fs';
import { join } from 'path';
import type { GroupConfig } from './group-resolver.js';
import type { User } from './user-resolver.js';
import { getOpenTasks, getOverdueTasksAll, getMemory, getRecentMemory, searchFacts, factsAbout, factsByPersonId, getFactsByType, peopleSearch, getRecentInteractions, type Fact, type Person, type Interaction } from './db.js';
import { toolRegistry } from './tools/index.js';
import { getProfileConfig } from './config.js';
import { getRoot, resolveSharedFile, resolveContextPath } from './paths.js';

const ROOT = getRoot();

let cachedIdentity: string | null = null;
let cachedSecurity: string | null = null;
let cachedVoice: string | null = null;
let cachedProfile: string | null = null;

function loadSharedFile(filename: string): string {
  const path = resolveSharedFile(filename);
  if (existsSync(path)) {
    return readFileSync(path, 'utf-8');
  }
  return '';
}

function getIdentity(): string {
  if (cachedIdentity === null) {
    cachedIdentity = loadSharedFile('identity.md');
  }
  return cachedIdentity;
}

function getSecurity(): string {
  if (cachedSecurity === null) {
    cachedSecurity = loadSharedFile('security.md');
  }
  return cachedSecurity;
}

function getVoice(): string {
  if (cachedVoice === null) {
    cachedVoice = loadSharedFile('voice.md');
  }
  return cachedVoice;
}

// The always-on background profile of the owner — who they are, what they're
// optimizing for, how to talk to them, the protected floor, the landmines.
// Generated by `npm run onboard` into context/shared/profile.md (gitignored).
// Granular versions of these facts also live in the `facts` table (seeded via
// scripts/seed-facts.ts) for on-demand retrieval; this narrative is the stable
// always-on layer. It loads into the cached staticPrefix, so the 5-min prompt
// cache absorbs its cost across an active back-and-forth.
function getProfile(): string {
  if (cachedProfile === null) {
    cachedProfile = loadSharedFile('profile.md');
  }
  return cachedProfile;
}

function loadSkills(contextPath: string): string {
  const skillsDir = join(ROOT, contextPath, 'skills');
  if (!existsSync(skillsDir)) return '';

  try {
    const files = readdirSync(skillsDir).filter((f) => f.endsWith('.md')).sort();
    if (files.length === 0) return '';

    const skills = files.map((f) => {
      const name = f.replace('.md', '');
      const content = readFileSync(join(skillsDir, f), 'utf-8');
      return `### Skill: ${name}\n${content}`;
    });

    return skills.join('\n\n');
  } catch {
    return '';
  }
}

// Precomputed date reference. LLMs are unreliable at date arithmetic ("the 13th"
// → which month, "next Tuesday" → which ISO date), and every downstream tool wants
// ISO (calendar `date` = YYYY-MM-DD, task `due_date` = ISO datetime). So instead of
// handing the model one prose timestamp and asking it to calculate, we hand it a
// lookup table of the next two weeks in ET. Arithmetic becomes a lookup.
function getDateReference(): string {
  const now = new Date();
  const timeStr = now.toLocaleString('en-US', {
    timeZone: 'America/New_York',
    dateStyle: 'full',
    timeStyle: 'short',
  });
  const todayIso = now.toLocaleDateString('en-CA', { timeZone: 'America/New_York' });
  const todayDow = now.toLocaleDateString('en-US', { timeZone: 'America/New_York', weekday: 'long' });

  // Anchor at noon UTC (= 7–8am ET) so adding whole days never crosses an ET day
  // boundary, even across a DST transition.
  const base = new Date(`${todayIso}T12:00:00Z`);
  const rows: string[] = [];
  for (let i = 0; i < 14; i++) {
    const d = new Date(base.getTime() + i * 86_400_000);
    const iso = d.toLocaleDateString('en-CA', { timeZone: 'America/New_York' });
    const label = d.toLocaleDateString('en-US', {
      timeZone: 'America/New_York',
      weekday: 'short',
      month: 'short',
      day: 'numeric',
    });
    const tag = i === 0 ? '  ← TODAY' : i === 1 ? '  ← tomorrow' : '';
    rows.push(`  ${label.padEnd(13)} → ${iso}${tag}`);
  }

  return [
    `Time: ${timeStr} ET`,
    `Today is ${todayDow}, ${todayIso}. This is the AUTHORITATIVE current date — never infer "today" from memory, conversation history, or training data.`,
    ``,
    `Date lookup (use these exact ISO dates — do NOT calculate dates yourself):`,
    ...rows,
    ``,
    `- A bare day number ("the 13th", "by the 5th") means the next future occurrence: that day this month if it hasn't passed, otherwise next month.`,
    `- Beyond the table above, count forward from TODAY's row.`,
    `- Always pass ISO dates (YYYY-MM-DD) to calendar and task tools, computed from this reference.`,
  ].join('\n');
}

function getSituationContext(): string {
  const now = new Date();
  const etHour = parseInt(now.toLocaleString('en-US', { timeZone: 'America/New_York', hour: 'numeric', hour12: false }));

  if (etHour < 9) return 'Early morning — keep it brief, focus on day prep';
  if (etHour < 12) return 'Morning — prime working hours';
  if (etHour < 14) return 'Midday — quick responses preferred';
  if (etHour < 17) return 'Afternoon — check if anything needs coordination before EOD';
  if (etHour < 21) return 'Evening — winding down, only surface urgent items';
  return 'Late night — only respond if critical';
}

function getTaskState(): string {
  try {
    const open = getOpenTasks();
    const overdue = getOverdueTasksAll();
    if (open.length === 0) return '';
    const header = `Backlog: ${open.length} open tasks${overdue.length > 0 ? ` (${overdue.length} overdue!)` : ''}`;
    // For a small backlog, list the actual tasks so "what reminders do I have"
    // is answerable straight from context. For a large backlog, keep the count
    // only (the agent can call list_tasks / recall_memory) to protect the budget.
    if (open.length > 8) return header;
    const lines = open.slice(0, 8).map((t) => {
      const due = t.due_date ? ` (due ${t.due_date.slice(0, 10)})` : '';
      return `  · #${t.id} ${t.title}${due}`;
    });
    return `${header}\n${lines.join('\n')}`;
  } catch {
    return '';
  }
}

const MEMORY_BLOCK_CHAR_CAP = 2000;
const RETRIEVAL_BUDGET_CHARS = 2500;
const LEARNED_PREF_MIN_CONFIDENCE = 0.7;

// Privacy scoping for retrieved facts. Facts flagged `sensitive` (relationship
// dynamic, private self-assessment, private finances) may only enter the
// retrieval blocks of MP-private groups. GROUP-based, not tone/sender-based:
// the Home group is a shared thread a household member can read even when the user (tone
// 'direct') is the one texting, so a tone gate would still leak there. This is
// a fail-CLOSED allowlist — any group not listed (today 'home', and any future
// group) gets sensitive facts stripped, even if user env is misconfigured.
// The narrative profile (getProfile) is separately tone-gated; this guards the
// fact layer. Durable column/seed support lands in db.ts + seed-facts.ts.
const SENSITIVE_OK_GROUPS = new Set([
  'admin', 'job-search', 'work', 'finance', 'health',
  'reflection', 'brain-pulse', 'idea-pulse', 'content',
]);

// Tokens that look like proper nouns (capitalized) but aren't meaningful entities —
// sentence-initial filler, weekday/month names, common interrogatives. Without this
// filter the People/Knowledge retrieval blocks fill with junk on day one.
const PROPER_NOUN_STOPWORDS = new Set([
  'i','what','whats','why','when','where','how','who','which','whose',
  'tell','show','give','let','lets','do','does','did',
  'monday','tuesday','wednesday','thursday','friday','saturday','sunday',
  'january','february','march','april','may','june',
  'july','august','september','october','november','december',
  'today','tomorrow','yesterday','tonight','morning','afternoon','evening','night',
  'the','a','an','and','or','but','if','then','so',
  'is','are','was','were','be','been','have','has','had',
  'can','could','will','would','should','may','might','must','shall',
  'this','that','these','those','it','they','we','you','he','she','his','her',
  'yes','no','okay','ok','please','thanks','thank',
]);

function extractProperNounCandidates(text: string): string[] {
  const tokens = text.match(/\b[A-Z][a-zA-Z'-]{1,}\b/g) || [];
  const out: string[] = [];
  const seen = new Set<string>();
  for (const t of tokens) {
    const lower = t.toLowerCase();
    if (PROPER_NOUN_STOPWORDS.has(lower)) continue;
    if (seen.has(lower)) continue;
    seen.add(lower);
    out.push(t);
  }
  return out;
}

function formatFactLine(f: Fact): string {
  const base = `- ${f.subject} ${f.predicate} ${f.object}`;
  return f.source && f.source !== 'manual' ? `${base} [${f.source}]` : base;
}

function dedupeFacts(list: Fact[]): Fact[] {
  const seen = new Set<number>();
  const out: Fact[] = [];
  for (const f of list) {
    if (!seen.has(f.id)) { seen.add(f.id); out.push(f); }
  }
  return out;
}

function formatPersonHeader(p: Person): string {
  const work = [p.role, p.company].filter(Boolean).join(' at ');
  const tags: string[] = [];
  if (work) tags.push(work);
  if (p.relationship) tags.push(p.relationship);
  if (p.last_contact) tags.push(`last contact ${p.last_contact.slice(0, 10)}`);
  return tags.length > 0 ? `- ${p.name} — ${tags.join(' · ')}` : `- ${p.name}`;
}

function formatInteractionLine(i: Interaction): string {
  const when = (i.occurred_at || i.created_at || '').slice(0, 10);
  const summary = i.summary || `(${i.channel || 'interaction'})`;
  return `    · ${when} ${summary}`;
}

function dedupePeople(list: Person[]): Person[] {
  const seen = new Set<number>();
  const out: Person[] = [];
  for (const p of list) {
    if (!seen.has(p.id)) { seen.add(p.id); out.push(p); }
  }
  return out;
}

// Renders Learned Preferences + Relevant Knowledge + People Context under a
// single shared budget. Without a combined cap, prompt growth compounds invisibly.
function getRetrievedBlocks(userMessage: string | undefined, groupKey: string): string {
  const sections: string[] = [];
  let budget = RETRIEVAL_BUDGET_CHARS;
  const properNouns = userMessage ? extractProperNounCandidates(userMessage) : [];

  // Privacy gate: in any group not on the MP-private allowlist (e.g. Home, which
  // a household member can read), strip facts flagged sensitive from EVERY block — Learned
  // Preferences, Relevant Knowledge, People Context — since getFactsByType,
  // factsAbout the owner or a household member and FTS can each surface the same payload.
  // Read `sensitive` via cast: the column exists in the live DB (added by the
  // import migration) but the committed Fact type in db.ts doesn't declare it
  // yet — that's the durable follow-up. Inline cast keeps this hotfix to one file.
  const allowSensitive = SENSITIVE_OK_GROUPS.has(groupKey);
  const visible = (fs: Fact[]): Fact[] =>
    allowSensitive ? fs : fs.filter((f) => !(f as { sensitive?: number | null }).sensitive);

  // Learned Preferences — high-confidence feedback + preferences, always injected.
  try {
    const learned = visible(getFactsByType(['feedback', 'preference'], 12))
      .filter((f) => (f.confidence ?? 1) >= LEARNED_PREF_MIN_CONFIDENCE);
    if (learned.length > 0) {
      const lines: string[] = ['\n--- Learned Preferences ---'];
      for (const f of learned) {
        const line = formatFactLine(f);
        if (line.length + 1 > budget) break;
        lines.push(line);
        budget -= line.length + 1;
      }
      if (lines.length > 1) sections.push(lines.join('\n'));
    }
  } catch { /* swallow — retrieval must never break prompt assembly */ }

  // Relevant Knowledge — only when the user sent a message.
  if (userMessage && budget > 80) {
    try {
      const ftsHits = searchFacts(userMessage, 8);
      const aboutHits = properNouns.flatMap((n) => factsAbout(n, 4));
      const merged = visible(dedupeFacts([...ftsHits, ...aboutHits]));
      if (merged.length > 0) {
        const lines: string[] = ['\n--- Relevant Knowledge ---'];
        let included = 0;
        for (const f of merged) {
          const line = formatFactLine(f);
          if (line.length + 1 > budget) {
            const remaining = merged.length - included;
            if (remaining > 0) lines.push(`- ... (${remaining} more truncated for budget)`);
            break;
          }
          lines.push(line);
          budget -= line.length + 1;
          included += 1;
        }
        if (lines.length > 1) sections.push(lines.join('\n'));
      }
    } catch { /* swallow */ }
  }

  // People Context — when the message names a person, surface their profile,
  // last interactions, and any facts linked to them via person_id. The
  // person_id lookup catches facts stored under subject strings that don't
  // string-match the person's display name (e.g. fact subject "aniket" when
  // the person's name is "Aniket Patel").
  if (userMessage && properNouns.length > 0 && budget > 80) {
    try {
      const peopleHits = dedupePeople(properNouns.flatMap((n) => peopleSearch(n, 2)));
      if (peopleHits.length > 0) {
        const lines: string[] = ['\n--- People Context ---'];
        let included = 0;
        for (const p of peopleHits.slice(0, 5)) {
          const header = formatPersonHeader(p);
          const interactions = getRecentInteractions(p.id, 2);
          const linkedFacts = visible(factsByPersonId(p.id, 3));
          const factLines = linkedFacts.map(formatFactLine).map((l) => l.replace(/^- /, '    · '));
          const block = [header, ...interactions.map(formatInteractionLine), ...factLines].join('\n');
          if (block.length + 1 > budget) {
            const remaining = peopleHits.length - included;
            if (remaining > 0) lines.push(`- ... (${remaining} more truncated for budget)`);
            break;
          }
          lines.push(block);
          budget -= block.length + 1;
          included += 1;
        }
        if (lines.length > 1) sections.push(lines.join('\n'));
      }
    } catch { /* swallow */ }
  }

  return sections.join('\n');
}

function getRecentMemoryBlock(groupKey: string): string {
  try {
    const seen = new Set<string>();
    const entries: { key: string; value: string; updated_at: string }[] = [];

    const latest = getMemory(groupKey, 'latest_context');
    if (latest) {
      entries.push({ key: 'latest_context', value: latest, updated_at: '' });
      seen.add('latest_context');
    }

    const checkpoints = getRecentMemory(groupKey, { prefix: 'checkpoint_', limit: 5 });
    for (const e of checkpoints) {
      if (!seen.has(e.key)) { entries.push(e); seen.add(e.key); }
    }

    const prefs = getRecentMemory(groupKey, { suffix: '_preference', limit: 10 });
    for (const e of prefs) {
      if (!seen.has(e.key)) { entries.push(e); seen.add(e.key); }
    }

    const priorities = getMemory(groupKey, 'current_priorities');
    if (priorities && !seen.has('current_priorities')) {
      entries.push({ key: 'current_priorities', value: priorities, updated_at: '' });
      seen.add('current_priorities');
    }

    const schedule = getMemory(groupKey, 'weekly_schedule_proposal');
    if (schedule && !seen.has('weekly_schedule_proposal')) {
      entries.push({ key: 'weekly_schedule_proposal', value: schedule, updated_at: '' });
      seen.add('weekly_schedule_proposal');
    }

    if (entries.length === 0) return '';

    const lines: string[] = [];
    let total = 0;
    for (const e of entries) {
      const line = `- ${e.key}: ${e.value}`;
      if (total + line.length > MEMORY_BLOCK_CHAR_CAP) {
        lines.push(`- ... (${entries.length - lines.length} more memory entries truncated)`);
        break;
      }
      lines.push(line);
      total += line.length + 1;
    }
    return lines.join('\n');
  } catch {
    return '';
  }
}

// The system prompt is built in two segments so each can get its own prompt-cache
// breakpoint (see agent.ts):
//   - `staticPrefix` — identity, voice, group context, skills, security, tool list
//     + routing. Stable for a given (group, user tone), so it caches ACROSS messages
//     within the 5-min TTL (during an active back-and-forth chat).
//   - `dynamic` — the live session block (date, situation, task counts), recent
//     memory, and per-message retrieval. Changes every minute/message, so it only
//     caches within a single agent run's tool loop.
// Cross-references that used to say "above"/"top" now say "below"/"in the session
// context" because the retrieval + date blocks moved into the dynamic suffix, which
// follows the static instructions.
export function loadSystemBlocks(
  group: GroupConfig,
  user: User,
  userMessage?: string,
): { staticPrefix: string; dynamic: string } {
  const staticParts: string[] = [];
  const dynamicParts: string[] = [];

  // ── Static prefix ─────────────────────────────────────────────────────────

  // Shared soul/identity
  const profileCfg = getProfileConfig();
  const identity = getIdentity();
  if (identity) {
    staticParts.push(identity);
  } else {
    staticParts.push(
      `You are ${profileCfg.botName}, a personal AI agent for the ${profileCfg.householdName}.`,
    );
  }

  // Voice / tone. the user (tone 'direct') gets the full operator voice guide —
  // this also covers the system user used by the scheduler / heartbeat /
  // brain-pulse, so proactive pings inherit the voice. the partner (tone 'warm')
  // stays on the warm directive. The voice block sits before Group Context so a
  // group's own outbound voice calibration loads after it and can override for
  // content drafting.
  if (user.tone === 'direct') {
    const voice = getVoice();
    if (voice) {
      staticParts.push('\n--- Voice ---');
      staticParts.push(voice);
    } else {
      staticParts.push('Tone: Be efficient and direct. No unnecessary pleasantries.');
    }
  } else if (user.tone === 'warm') {
    staticParts.push('Tone: Be warm, friendly, and helpful. Use a conversational tone.');
  }

  // Always-on profile of MP. Gated to tone 'direct' — that's the user plus the
  // system user the scheduler / heartbeat / brain-pulse run as, so every
  // MP-facing surface (live chat + proactive loops) gets it, while the partner's
  // warm-tone sessions never see the relationship candor it contains. Sits in
  // the cached staticPrefix so its size is absorbed by the cross-message cache.
  if (user.tone === 'direct') {
    const profile = getProfile();
    if (profile) {
      staticParts.push(`\n--- About ${profileCfg.owner.name} ---`);
      staticParts.push(profile);
    }
  }

  // Group CLAUDE.md
  const claudePath = join(ROOT, group.contextPath, 'CLAUDE.md');
  if (existsSync(claudePath)) {
    const content = readFileSync(claudePath, 'utf-8');
    staticParts.push('\n--- Group Context ---');
    staticParts.push(content);
  }

  // Skills
  const skills = loadSkills(group.contextPath);
  if (skills) {
    staticParts.push('\n--- Skills ---');
    staticParts.push('Follow these workflows step-by-step when triggered. Show your progress to the user as you work through each step.');
    staticParts.push(skills);
  }

  // Security
  const security = getSecurity();
  if (security) {
    staticParts.push('\n--- Security Rules ---');
    staticParts.push(security);
  }

  // Tool scope + routing — list the actual callable tool names (the names
  // the Anthropic API will accept), not the group-key abstractions. Otherwise
  // the system prompt claims tools like "browser" exist when the only callable
  // is "browser_action" / "clip_to_facts".
  staticParts.push(`\n--- Tools ---`);
  const callableNames = group.tools
    .flatMap((key) => toolRegistry[key] || [])
    .map((t) => t.definition.name);
  const uniqueCallable = Array.from(new Set(callableNames));
  staticParts.push(`Available tools: ${uniqueCallable.join(', ')}`);
  staticParts.push('Only use tools that are listed above. If the user asks for something outside your tool scope, let them know which group handles it.');
  staticParts.push(`All tasks created via create_task automatically sync to Google Tasks on ${profileCfg.owner.name}'s phone. There is no separate reminder system.`);

  staticParts.push(`\n--- Tool Routing ---`);
  staticParts.push('- CHECK BEFORE CLAIMING IGNORANCE: before telling the user you don\'t have a note, fact, reminder, person, or task about something — OR when he asks "what do you have on X" / "what did I tell you about Y" / "what are you tracking" — call recall_memory("<subject>") (or omit the subject for an overview). It pulls everything across facts, people, tasks, and messages in one shot and sees data the context blocks below may have dropped. Never say "I don\'t have that" without calling it first.');
  staticParts.push('- Mentions of a meeting, event, "tomorrow", a day-of-week → list_events FIRST.');
  staticParts.push('- Mentions of a person by name → check the --- People Context --- and --- Relevant Knowledge --- blocks in the session context below first; if not there, call find_person("<name>") or facts_about("<name>"). Save durable info about people with note_about_person.');
  staticParts.push('- Anything the user "needs to do later" → create_task.');
  staticParts.push('- User defers a surfaced task ("snooze", "remind me later", "not now", "tomorrow", "Friday") → call snooze_task(id, <ISO>) IMMEDIATELY. Resolve the date from the Date lookup in the session context below ("3 days from now" → find TODAY + 3 rows), at 9am ET unless they say otherwise.');
  staticParts.push('- User cancels a surfaced task ("cancel", "skip", "drop it", "not doing X") → call cancel_task(id) IMMEDIATELY. Don\'t just acknowledge — the heartbeat will keep re-pinging until the DB is mutated.');
  staticParts.push('- The task #id is the surfaced number — pull it from the most recent heartbeat message in conversation history.');
  staticParts.push('- Atomic facts with a clear subject (person, project, deadline) → save_fact. Use fact_type "preference" / "decision" / "metric" for things that change over time (they supersede prior values).');
  staticParts.push('- Generic notes / state without a subject → remember.');
  staticParts.push('- End of a substantive conversation → memory_checkpoint.');
  staticParts.push('- Hit a real-world wall (login, phone call, signature) → assign_human_task.');

  staticParts.push(`\n--- Anticipate ---`);
  staticParts.push('After answering, briefly consider: is there anything worth remembering? Does this imply a follow-up task? Should this go on the calendar? If yes to any, do it before ending the turn — don\'t ask permission for low-stakes saves. Prefer save_fact over remember whenever you can name a subject (person, project, entity).');

  // ── Dynamic suffix ────────────────────────────────────────────────────────

  // Live session block (the date table is the load-bearing piece — see getDateReference)
  dynamicParts.push(`\n--- Session ---`);
  dynamicParts.push(`Group: ${group.name}`);
  dynamicParts.push(`Sender: ${user.name} (${user.role})`);
  dynamicParts.push(getDateReference());
  dynamicParts.push(`Context: ${getSituationContext()}`);
  const taskState = getTaskState();
  if (taskState) dynamicParts.push(taskState);

  // Recent Memory (surfaces persistent state so memory isn't write-only)
  const memoryBlock = getRecentMemoryBlock(group.key);
  if (memoryBlock) {
    dynamicParts.push('\n--- Recent Memory ---');
    dynamicParts.push(memoryBlock);
  }

  // Retrieved knowledge: Learned Preferences (always) + Relevant Knowledge
  // (when there's an inbound user message). Shared ~2500 char budget.
  const retrieved = getRetrievedBlocks(userMessage, group.key);
  if (retrieved) dynamicParts.push(retrieved);

  // Voice-memo nudge: a long voice rant is usually thinking-out-loud, not a question.
  // Default to fact extraction over a chatty reply.
  if (userMessage && userMessage.startsWith('[Voice message]:') && userMessage.length > 300) {
    dynamicParts.push(`\n--- Voice Memo Mode ---`);
    dynamicParts.push('This is a long voice memo — likely the user thinking out loud, not asking a direct question. Prioritize extracting durable facts via save_fact (decisions, commitments, new people, ideas worth remembering) over a chatty response. A short ack ("got it, saved X, Y, Z") is usually enough.');
  }

  return { staticPrefix: staticParts.join('\n'), dynamic: dynamicParts.join('\n') };
}

export function loadSystemPrompt(group: GroupConfig, user: User, userMessage?: string): string {
  const { staticPrefix, dynamic } = loadSystemBlocks(group, user, userMessage);
  return `${staticPrefix}\n${dynamic}`;
}
